version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tank
      MYSQL_DATABASE: tank
      MYSQL_USER: tank
      MYSQL_PASSWORD: tank
#  tomcat:
volumes:
    db_data:
