version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xms1g -Xmx2g"
    SKIP_METHODTIMER_TEST: true
    SKIP_GUI_TEST: true

phases:
  install:
    runtime-versions:
      java: corretto23
  build:
    commands:
      - java -version
      # Run the complete build with both unit and integration tests
      - mvn clean install surefire-report:report -P release

reports:
  UnitTestReports:
    files:
      - '**/target/surefire-reports/TEST-*.xml'
      - '**/target/surefire-reports/*.txt'
    base-directory: '.'
  IntegrationTestReports:
    files:
      - '**/target/failsafe-reports/TEST-*.xml'
      - '**/target/failsafe-reports/*.txt'
    base-directory: '.'

artifacts:
  files:
    - web/web_ui/target/tank.war
    - agent/agent_startup_pkg/target/agent-startup-pkg.zip
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
