version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xms1g -Xmx2g"

phases:
  build:
    commands:
      - mvn clean install -P release -Dmaven.test.skip=true

artifacts:
  type: NONE
  files:
    - web/web_ui/target/tank.war
    - agent/agent_startup_pkg/target/agent-startup-pkg.zip
  discard-paths: yes
