version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xms1g -Xmx2g"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn clean install -P release

artifacts:
  type: NONE
  files:
    - web/web_ui/target/tank.war
    - agent/agent_startup_pkg/target/agent-startup-pkg.zip
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
