/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : dangleton
 * Created : 04/04/2015 02:13:09
 */

package com.intuit.tank.harness;

import com.intuit.tank.test.TestGroups;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;


public class AgentUtilTest {

    /**
     *
     * @see com.intuit.tank.harness.AgentUtil#validateTestPlans(String)
     */
    @Test
    @Tag(TestGroups.FUNCTIONAL)
    public void validateTestPlans() {
    	boolean result = AgentUtil.validateTestPlans("");
    	assertNotNull(result, "result cannot be null");
    }

	
}
