/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : dangleton
 * Created : 04/04/2015 02:13:09
 */

package com.intuit.tank.harness;

import com.intuit.tank.test.TestGroups;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;


public class AgentUtilTest {

    /**
     *
     * @see com.intuit.tank.harness.AgentUtil#validateTestPlans(String)
     */
    @Test
    @Tag(TestGroups.FUNCTIONAL)
    public void validateTestPlans_Empty() {
    	boolean result = AgentUtil.validateTestPlans("");
    	assertFalse(result, "TestPlan list should not be null");
    }

    @Test
    @Tag(TestGroups.FUNCTIONAL)
    public void validateTestPlans_Good() {
        boolean result = AgentUtil.validateTestPlans("src/test/resources/TEST_H.xml");
        assertTrue(result, "Test file should exists");
    }

    @Test
    @Tag(TestGroups.FUNCTIONAL)
    public void validateTestPlans_Bad() {
        boolean result = AgentUtil.validateTestPlans("NOTFOUND.xml");
        assertFalse(result, "File should not be found");
    }

    @Test
    @Tag(TestGroups.FUNCTIONAL)
    public void validateTestPlans_Bad2() {
        boolean result = AgentUtil.validateTestPlans("src/test/resources/TEST_H.xml, NOTFOUND.xml");
        assertFalse(result, "Contains a File Not Found in list");
    }
}
