/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : dangleton
 * Created : 04/04/2015 02:13:09
 */

package com.intuit.tank.harness;

import static org.testng.Assert.assertNotNull;

import org.testng.annotations.Test;

import com.intuit.tank.test.TestGroups;



public class AgentUtilTest {

    /**
     *
     * @see com.intuit.tank.harness.AgentUtil#validateTestPlans(String)
     */
    @Test(groups =  TestGroups.FUNCTIONAL )
    public void validateTestPlans() {
    	boolean result = AgentUtil.validateTestPlans("");
    	assertNotNull(result, "result cannot be null");
    }

	
}
