// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.intuit.tank.project;

/*
 * #%L
 * Intuit Tank data model
 * %%
 * Copyright (C) 2011 - 2015 Intuit Inc.
 * %%
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * #L%
 */

import java.util.Date;

public class SummaryDataBuilder extends SummaryDataBuilderBase<SummaryDataBuilder> {
    public static SummaryDataBuilder summaryData() {
        return new SummaryDataBuilder();
    }

    public SummaryDataBuilder() {
        super(new SummaryData());
    }

    public SummaryData build() {
        return getInstance();
    }
}

class SummaryDataBuilderBase<GeneratorT extends SummaryDataBuilderBase<GeneratorT>> {
    private SummaryData instance;

    protected SummaryDataBuilderBase(SummaryData aInstance) {
        instance = aInstance;
    }

    protected SummaryData getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withJobId(int aValue) {
        instance.setJobId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPageId(String aValue) {
        instance.setPageId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSampleSize(int aValue) {
        instance.setSampleSize(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withMean(double aValue) {
        instance.setMean(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withMin(double aValue) {
        instance.setMin(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withMax(double aValue) {
        instance.setMax(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSttDev(double aValue) {
        instance.setSttDev(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withKurtosis(double aValue) {
        instance.setKurtosis(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSkewness(double aValue) {
        instance.setSkewness(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withVarience(double aValue) {
        instance.setVarience(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile10(double aValue) {
        instance.setPercentile10(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile20(double aValue) {
        instance.setPercentile20(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile30(double aValue) {
        instance.setPercentile30(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile40(double aValue) {
        instance.setPercentile40(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile50(double aValue) {
        instance.setPercentile50(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile60(double aValue) {
        instance.setPercentile60(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile70(double aValue) {
        instance.setPercentile70(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile80(double aValue) {
        instance.setPercentile80(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile90(double aValue) {
        instance.setPercentile90(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile95(double aValue) {
        instance.setPercentile95(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPercentile99(double aValue) {
        instance.setPercentile99(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(int aValue) {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreated(Date aValue) {
        instance.setCreated(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withModified(Date aValue) {
        instance.setModified(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withForceCreateDate(Date aValue) {
        instance.setForceCreateDate(aValue);

        return (GeneratorT) this;
    }
}
