AWSTemplateFormatVersion: 2010-09-09
Description: Controller Instance - Creates a Tank controller installing java tomcat and configuring the instances appropriately.
Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: The ID of the latest Amazon Linux 2 baseline AMI
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for the internal instance ip
  TankWar:
    Type: String
    Description: File path to Tank tank.war Filename in S3 (ie. s3://bucket/keyname)
  TankSettings:
    Type: String
    Description: File path to Tank settings.xml Filename in S3 (ie. s3://bucket/keyname)
  RdsPassword:
    Type: String
    NoEcho: true
    Description: Something secret (more than 8 characters)
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: 't4g.large'
    AllowedValues: [ 't3a.medium', 't4g.medium', 't3a.large', 't4g.large', 't3a.xlarge', 't4g.xlarge', 'm6i.large', 'm6i.xlarge', 'c6i.xlarge', 'c6i.2xlarge' ]
    ConstraintDescription: 'Must be one of t4g.medium t4g.large t4g.xlarge m6i.large m6i.xlarge c6i.xlarge or c6i.2xlarge'

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: tank
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t3.large
      Port: 3306
      AllocatedStorage: 100
      BackupRetentionPeriod: 30
      DBName: tank
      Engine: mysql
      EngineVersion: 8.0.21
      MasterUsername: admin
      MasterUserPassword: !Ref RdsPassword
      DBSecurityGroups:
        - !Ref RDSSecurityGroup

  RDSSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Ingress for Amazon EC2 security group
      DBSecurityGroupIngress:
        - EC2SecurityGroupName: !Ref SecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http tomcat to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  ControllerInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default: ['metric-config', 'tomcat-config' ]
        metric-config:
          packages:
            yum:
              amazon-cloudwatch-agent: []
            rpm:
              xray-daemon: !Sub 'https://s3.dualstack.${AWS::Region}.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm'
          groups: {}
          users: {}
          sources: {}
          files:
            /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/tank-cloudwatch-config.json:
              content: |
                {"logs":{"force_flush_interval":5,"logs_collected":{
                  "files":{"collect_list":[
                    {"file_path":"/var/log/tomcat/catalina*.log","log_group_name":"/var/log/tomcat/catalina.log","log_stream_name":"{instance_id}"},
                    {"file_path":"/var/log/tomcat/tank.log","log_group_name":"/var/log/tomcat/tank.log","log_stream_name":"{instance_id}"},
                    {"file_path":"/var/log/tomcat/gc.log","log_group_name":"/var/log/tomcat/gc.log","log_stream_name":"{instance_id}"},
                    {"file_path":"/var/log/messages","log_group_name":"/var/log/messages","log_stream_name":"{instance_id}"}]}}},
                  "metrics":{"append_dimensions":{"InstanceId":"${aws:InstanceId}","InstanceType":"${aws:InstanceType}"},"metrics_collected":{
                    "disk":{"measurement":["used_percent"],"resources":["/"],"append_dimensions":{"Service":"Tank"},"metrics_collection_interval":60},
                    "mem":{"measurement":["mem_used_percent"],"append_dimensions":{"Service":"Tank"},"metrics_collection_interval":60}}}}
              mode: '000644'
              owner: 'cwagent'
              group: 'cwagent'
          commands: {}
          services:
              amazon-cloudwatch-agent:
                enabled      : true
                ensureRunning: true
                files:
                  - "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/tank-cloudwatch-config.json"
        tomcat-config:
          packages:
            yum:
              tomcat-native: []
              java-17-amazon-corretto-headless: []
          users:
            tomcat: {}
          groups: {}
          sources:
            /opt: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz
          files:
            /etc/init.d/tomcat:
              content: |
                #!/bin/bash
                #
                # tomcat         Start tomcat
                #
                #
                # chkconfig: 345 88 12
                # description: start stop tomcat
                ### BEGIN INIT INFO
                # Provides: $tomcat
                ### END INIT INFO
                # Source function library.
                . /etc/init.d/functions
                . /etc/init.d/java_opts

                ulimit -n 50000
                export CATALINA_HOME=/opt/tomcat
                RETVAL=0
                umask 077
                start() {
                       cd $CATALINA_HOME
                       echo -n $"Starting tomcat: "
                       daemon $CATALINA_HOME/bin/startup.sh
                       echo
                       return $RETVAL
                }
                stop() {
                       echo -n $"Shutting down tomcat: "
                       daemon $CATALINA_HOME/bin/shutdown.sh
                       echo
                       return $RETVAL
                }
                restart() {
                       stop
                       start
                }
                case "$1" in
                 start)
                       start
                       ;;
                 stop)
                       stop
                       ;;
                 restart|reload)
                       restart
                       ;;
                 *)
                       echo $"Usage: $0 {start|stop|restart}"
                       exit 1
                esac
                exit $?
              mode: '000755'
              owner: 'tomcat'
              group: 'tomcat'
            /etc/init.d/java_opts:
              content: |
                export CATALINA_OPTS="-XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Xlog:gc=debug:file=/var/log/tomcat/gc.log:time,uptime,level,tags:filecount=3,filesize=200m"
              mode: '000755'
              owner: 'tomcat'
              group: 'tomcat'
            /tmp/context.xml:
              content: !Sub |
                <?xml version="1.0" encoding="UTF-8"?>

                <Context>
                    <Resource name="jdbc/watsDS" auth="Container"
                    type="javax.sql.DataSource"
                    factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
                    maxWait="10000"
                    username="admin"  password="${RdsPassword}"
                    testOnBorrow="true"
                    validationQuery="SELECT 1"
                    removeAbandonedOnBorrow="true"
                    removeAbandonedOnMaintenance="true"
                    removeAbandonedTimeout="60"
                    driverClassName="com.mysql.cj.jdbc.Driver"
                    jdbcInterceptors="com.amazonaws.xray.sql.mysql.TracingInterceptor"
                    url="jdbc:mysql://${RDSInstance.Endpoint.Address}:${RDSInstance.Endpoint.Port}/tank"/>
                </Context>
              mode: '000644'
              owner: 'tomcat'
              group: 'tomcat'
          commands:
            010_tomcat_symboliclink:
              command: 'ln -s /opt/apache-tomcat-10.1.16 /opt/tomcat'
            011_tomcat_symboliclink:
              command: 'ln -s /opt/tomcat/logs /var/log/tomcat'
            020_clear_out_builtin:
              command: 'rm -rf /opt/tomcat/webapps/*'
            030_download_settings:
              command: !Sub 'aws s3 cp ${TankSettings} /usr/share/tomcat/settings.xml'
            031_permissions:
              command:  'chown tomcat:tomcat /usr/share/tomcat/settings.xml'
            050_copy_context:
              command: 'cp /tmp/context.xml /opt/tomcat/conf/context.xml'
            #031_set_publicDNSName:
            #  command: !Sub 'sed -i "s/localhost:8080/${ControllerInstance.PublicDnsName}:8080/" /usr/share/tomcat/settings.xml'
            060_download_tank:
              command: !Sub 'aws s3 cp ${TankWar} /usr/share/tomcat/webapps/ROOT.war'
            070_permissions:
              command: 'chown -R tomcat:tomcat /opt/apache-tomcat-10.1.16'
          services:
            sysvinit:
              tomcat:
                enabled      : true
                ensureRunning: true
    Properties:
      ImageId:  !Ref AmiId
      InstanceType:  !Ref InstanceType
      IamInstanceProfile: !ImportValue TankControllerProfile
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      Tags:
        -
          Key: Name
          Value: Tank
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -v
          # Ensure our PATH is set correctly (on Amazon Linux cfn-signal is in /opt/aws/bin)
          . ~/.bash_profile
          yum update -y
          /opt/aws/bin/cfn-init -v \
            --region  ${AWS::Region} \
            --stack   ${AWS::StackName} \
            --resource ControllerInstance
          /opt/aws/bin/cfn-signal -e $? \
            --region  ${AWS::Region} \
            --stack   ${AWS::StackName} \
            '${UIInstanceWaitHandle}'
  UIInstanceWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
  UIInstanceWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: ControllerInstance
    Properties:
      Handle:  !Ref UIInstanceWaitHandle
      Timeout: 1800

Outputs:
  InstanceId:
    Description: InstanceId of the newly created controller instance
    Value:  !Ref ControllerInstance
  PublicDnsName:
    Description: PublicDnsName endpoint of the newly created ControllerInstance
    Value:  !GetAtt [ 'ControllerInstance', 'PublicDnsName' ]
