AWSTemplateFormatVersion: 2010-09-09
Description: Create Controller and Agent IAM Instance Profiles for Intuit/Tank installation
Resources:
  ControllerProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref ControllerRole
  ControllerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        -
          PolicyName: tank-controller-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:ListInstanceProfiles
                  - iam:AddRoleToInstanceProfile
                  - appconfig:GetConfiguration
                Resource: "*"
  AgentProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref AgentRole
  AgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

Outputs:
  TankControllerProfile:
    Description: Tank Controller Profile
    Value:  !Ref ControllerProfile
    Export:
      Name:  TankControllerProfile
  TankControllerRole:
    Description: Tank Controller Role
    Value:  !Ref ControllerRole
    Export:
      Name:  TankControllerRole
  TankAgentProfile:
    Description: Tank Agent Profile
    Value:  !Ref AgentProfile
    Export:
      Name:  TankAgentProfile
  TankAgentRole:
    Description: Tank Agent Role
    Value:  !Ref AgentRole
    Export:
      Name:  TankAgentRole
