#!/bin/bash
# tank-agent
# chkconfig: 345 99 12
# description: agent for Tank project
### BEGIN INIT INFO
# Provides: $tank-agent
### END INIT INFO

# Source function library.
. /etc/init.d/functions

RETVAL=0

umask 077

start() {
       echo -n $"Starting Tank Agent: "
       pushd /opt/tank_agent
       ulimit -n 20000;
       ulimit -a >> /tmp/ulimit_out;
       daemon /opt/tank_agent/run.sh&
       echo
       return $RETVAL
}
stop() {
       echo -n $"Shutdown agent startup: "
       kill -9 `ps -ef | grep agent-startup-all | grep -v grep | awk '{print $2}'`
       return $RETVAL
}
restart() {
       stop
       start
}
case "$1" in
 start)
       start
       ;;
 stop)
       stop
       ;;
 restart|reload)
       restart
       ;;
 *)
       echo $"Usage: $0 {start|stop|restart}"
       exit 1
esac

exit $?
