name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important: auto needs full git history

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: auto shipit